...

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,37 +1,36 @@
 #!/usr/bin/env bash
-# Installs Nginx with the following configurations:
-#+    Listens on port 80.
-#+    Returns a page containing "Hello World!" when queried
-#+     at the root with a curl GET request.
-#+    Configures /redirect_me as a "301 Moved Permanently".
-#+    Includes a custom 404 page containing "Ceci n'est pas une page".
-#+    Contains a custom HTTP header named X-Served-By.
-#+    The value of the HTTP header is the hostname of the running server.
+sudo apt-get update
+sudo apt-get install -y nginx
 
-apt-get install -y nginx
+custom_header_name="X-Served-By"
+server_hostname=$(hostname)
 
-mkdir -p /var/www/html
-touch /var/www/html/index.html
-echo "Hello World!" > /var/www/html/index.html
-touch /var/www/html/404.html
-echo "Ceci n'est pas une page" > /var/www/html/404.html
-
-printf %s "server {
+echo "Adding custom header to Nginx configuration..."
+sudo bash -c "cat > /etc/nginx/sites-available/default" <<EOF
+server {
     listen 80 default_server;
     listen [::]:80 default_server;
-    add_header X-Served-By $HOSTNAME;
-    root   /var/www/html;
-    index  index.html index.htm;
 
-    location /redirect_me {
-        return 301 http://facebook.com/;
+    server_name _;
+
+    location / {
+        add_header $custom_header_name $server_hostname;
+        # Other Nginx configuration settings
+        # ...
     }
 
-    error_page 404 /404.html;
-    location /404 {
-      root /var/www/html;
-      internal;
-    }
-}" > /etc/nginx/sites-available/default
+    # Additional server blocks and configurations if needed
+}
+EOF
 
-service nginx restart
+echo "Testing Nginx configuration..."
+sudo nginx -t
+
+if [ $? -eq 0 ]; then
+    echo "Restarting Nginx..."
+    sudo service nginx restart
+else
+    echo "Error: Nginx configuration test failed. Please check the configuration."
+fi
+
+echo "Configuration completed."
