new files

diff --git a/0x0E-web_stack_debugging_1/0-nginx_likes_port_80 b/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
--- a/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
+++ b/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
@@ -1,31 +1,17 @@
 #!/usr/bin/env bash
-sudo apt update
-sudo apt install -y net-tools
+sudo apt-get update
+sudo apt-get install -y net-tools
 
-nginx_status=$(sudo service nginx status)
-echo "Nginx Status: $nginx_status"
+sudo service nginx start
 
-nginx_conf="/etc/nginx/nginx.conf"
-nginx_site_conf="/etc/nginx/sites-available/default"
-
-if [ -f "$nginx_conf" ]; then
-    echo "Checking $nginx_conf"
-
-else
-    echo "$nginx_conf not found!"
+if ! grep -q "listen 80 default_server;" /etc/nginx/sites-available/default; then
+    sudo sed -i '/server_name _;/a \\\tlisten 80 default_server;' /etc/nginx/sites-available/default
 fi
-
-if [ -f "$nginx_site_conf" ]; then
-    echo "Checking $nginx_site_conf"
-
-else
-    echo "$nginx_site_conf not found!"
-fi
-
-nginx_test=$(sudo nginx -t 2>&1)
-echo "Nginx Configuration Test: $nginx_test"
 
 sudo service nginx restart
 
-nginx_status=$(sudo service nginx status)
-echo "Nginx Status after restart: $nginx_status"
+if sudo netstat -tulpn | grep -q ":80"; then
+    echo "Nginx is now listening on port 80."
+else
+    echo "Failed to configure Nginx to listen on port 80."
+fi
